### ISSUE TITLE
Add support for issue labels

### ISSUE THREAD

**Issue by bdbch** [jacquerie/github-file#5]
I think this is a great idea to configure your repositories. Adding issue labels is very annoying for me, since I like to use my labels to organise my private projects as well.

Do you think it's possible to add Label support too?

**Comment by jacquerie** [comment]
> Do you think it's possible to add Label support too?

There are [API endpoints to do CRUD on labels](https://developer.github.com/v3/issues/labels/#list-all-labels-for-this-repository), and [`github3.py` appears to support them](https://github.com/sigmavirus24/github3.py/blob/0452d7be71659eba4d0bc3794fc342e795fb2dc5/github3/repos/repo.py), so in theory it should be possible. On the other hand I can't think of a good configuration format. Maybe something like
```ini
[core]
...
labels = bug:bd2c00, help wanted:c9510c, ...
```
?

**Comment by jacquerie** [comment]
Mh, but using `:` as a separator is a bad idea, since I've seen people using it in label names... Perhaps
```ini
[core]
...
labels = help wanted, c9510c
    good first issue, 6cc644
    bug, bd2c00
```
?

**Comment by bdbch** [comment]
I think that looks okay for me! Should give it a try.

**Comment by jacquerie** [comment]
I just noticed that [`github3.py` doesn't yet support label descriptions](https://github.com/sigmavirus24/github3.py/pull/852), which is not essential, but nice to have.

**Comment by jacquerie** [comment]
> I think that looks okay for me! Should give it a try.

In https://github.com/jacquerie/github-file/commit/536ccdc3c4dc98213988015c10d9d2d2c78d3812 I implemented what I proposed in https://github.com/jacquerie/github-file/issues/5#issuecomment-405615064, except that I put them in the `[issues]` section instead of `[core]`. Do you mind giving it a spin on a test repository?

**Comment by jacquerie** [comment]
@bdbch The `develop` branch now has this feature, as documented by this test: https://github.com/jacquerie/github-file/blob/adf2ad9deab03f2bb615c4fab7be1542beedd3da/tests/test_cli.py. It can't be merged on `master`, and therefore deployed on PyPI, until I get a release of `github3.py`, something which I can't really predict when it will happen...

**Comment by jacquerie** [comment]
> something which I can't really predict when it will happen...

It happened! :tada:

**Comment by jacquerie** [comment]
Done in https://github.com/jacquerie/github-file/pull/6.
